export const types = {
    SET_DATA: "SET-DATA",
    UPDATE_BOXES: "UPDATE-BOXES",
    UPDATE_ACTIVE: "UPDATE-ACTIVE",
    UPDATE_SEARCH_VALUE: "UPDATE-SEARCH-VALUE",
    BURGER_TOGGLE: "BURGER-TOGGLE",
}